#!/usr/bin/env python3
"""Checks the generated pronunciation audio before it ships.

    python3 scripts/content/qa_audio.py
    python3 scripts/content/qa_audio.py --json report.json

Synthesis fails quietly. A provider under load returns a valid MP3 containing
silence; a retry loop writes the same clip twice under two voice names; a
truncated download still has an ID3 header. None of that is visible by looking
at a directory listing, and all of it reaches a paying customer as "the speaker
button does nothing".

So every clip is checked against the thing it claims to be:

* it exists, is not empty, and actually decodes
* its duration is plausible for the number of syllables it should contain
* it is not silent, and its loudness landed near the normalisation target
* the female and male clips of the same text are genuinely different audio
* the manifest says the same text the speech plan asked for
* every planned clip has both voices

Failures are errors; the oddities that are usually fine are warnings.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import json
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from hangul import is_syllable, romanize  # noqa: E402
from tts import LOUDNESS_TARGET_LUFS, PROVIDERS, SPEECH_RATE  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
PUBLIC = ROOT / "apps" / "web" / "public"
#: The corpus being checked.
#:
#: `--root` points it somewhere other than the shipped directory, which is what
#: a *voice change* needs: the new corpus is generated beside the old one and
#: has to pass before anything is replaced. See §59 — nothing is deleted until
#: the replacement has been checked.
MANIFEST = PUBLIC / "audio" / "manifest.json"
AUDIO_DIR = PUBLIC / "audio"


def _declared_rate(provider_id: str) -> float | None:
    """The pace the engine that made this corpus says it speaks at.

    Not every engine can be asked to slow down. The ones registered here all
    take a rate parameter and derive it from `SPEECH_RATE`; one that cannot
    declares `spoken_rate = 1.0` instead, and a corpus it produced must be
    measured against *that* rather than against a slowness it was never asked
    for — which is how five perfectly good clips once came back "too short" by
    ten milliseconds.

    Resolved from the provider registry rather than from a list of names here,
    so a new engine states its own pace in one place and this check follows.
    Returns None for a provider this build does not know, which is a manifest
    generated by something no longer in the tree.
    """
    for provider in PROVIDERS.values():
        if provider.id == provider_id:
            return provider.spoken_rate
    return None


def clip_path(src: str) -> Path:
    """`audio/words/female/x.mp3` → the file, wherever this corpus lives.

    The manifest always writes the path the *app* asks for, which starts with
    `audio/`, because that is what has to be true in the shipped build. A staged
    corpus lives somewhere else, so the prefix is stripped and re-rooted rather
    than the manifest being written differently for a check — a manifest that
    differed between the check and the release would be checking a file the
    product will never load.
    """
    return AUDIO_DIR / src.removeprefix("audio/")
PLAN = ROOT / "content-cache" / "speech-plan.json"

#: A Korean syllable takes roughly a fifth of a second to say. The bounds are
#: wide because a lone vowel is fast and a sentence has pauses — this catches
#: "returned 60 ms of nothing" and "returned the wrong, much longer text",
#: not natural variation.
#:
#: Every bound is stated at conversational pace and then divided by the rate the
#: clips were actually spoken at, so slowing the voices down does not quietly
#: widen the "too short" test into uselessness. See ``SPEECH_RATE`` in tts.py.
#: Overwritten from the manifest in `main`, because the rate is a property of
#: the corpus being checked rather than of this file. A corpus generated by an
#: engine with no rate control records 1.0 and is measured against 1.0.
_TEMPO = max(0.1, SPEECH_RATE)
MS_PER_SYLLABLE_MIN = round(90 / _TEMPO)
MS_PER_SYLLABLE_MAX = round(900 / _TEMPO)
#: A single short vowel really is about a sixth of a second. Below this it is
#: clipped rather than brief — measured against the male 이 and 으 clips, which
#: land at 144 ms at full speed and are perfectly audible.
ABSOLUTE_MIN_MS = round(120 / _TEMPO)
ABSOLUTE_MAX_MS = round(12_000 / _TEMPO)

#: Below this a clip is silence with a bitrate.
SILENCE_FLOOR_DB = -50.0
#: How far from the −16 LUFS target a clip may land before it is worth saying so.
LOUDNESS_TOLERANCE_DB = 6.0


@dataclass
class Report:
    checked: int = 0
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    total_bytes: int = 0
    durations: list[int] = field(default_factory=list)

    def error(self, message: str) -> None:
        self.errors.append(message)

    def warn(self, message: str) -> None:
        self.warnings.append(message)


_VOLUME = re.compile(r"(mean_volume|max_volume):\s*(-?\d+(?:\.\d+)?) dB")


#: `Duration: 00:00:00.46,` out of ffmpeg's own header dump.
_DURATION = re.compile(r"Duration:\s*(\d+):(\d\d):(\d\d(?:\.\d+)?)")


def measure(path: Path) -> tuple[float, float, float]:
    """(duration_ms, mean_dB, max_dB). Raises if the file does not decode.

    One subprocess, not two. `volumedetect` has to decode the whole file to
    report a mean, and ffmpeg prints the container duration in the same stderr
    it prints the levels in — so asking ffprobe for the duration afterwards was
    decoding nothing new and doubling the process count. Over 10,454 clips that
    was 10,454 processes and about four minutes of pure fork overhead.

    The header duration and ffprobe's differ by a few milliseconds on VBR
    (0.46 against 0.456 on the first clip). Both bounds this feeds are hundreds
    of milliseconds wide and exist to catch "returned 60 ms of nothing", so the
    difference is far below anything being asked. ffprobe is still there for the
    case that matters — a file whose header carries no duration at all.
    """
    result = subprocess.run(
        ["ffmpeg", "-hide_banner", "-nostats", "-i", str(path), "-af", "volumedetect",
         "-f", "null", "-"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip().splitlines()[-1] if result.stderr else "decode failed")
    levels = {m.group(1): float(m.group(2)) for m in _VOLUME.finditer(result.stderr)}

    found = _DURATION.search(result.stderr)
    if found:
        hours, minutes, seconds = found.groups()
        duration_ms = (int(hours) * 3600 + int(minutes) * 60 + float(seconds)) * 1000
    else:
        probe = subprocess.run(
            ["ffprobe", "-v", "error", "-show_entries", "format=duration",
             "-of", "default=noprint_wrappers=1:nokey=1", str(path)],
            capture_output=True,
            text=True,
            check=True,
        )
        duration_ms = float(probe.stdout.strip()) * 1000
    return duration_ms, levels.get("mean_volume", -99.0), levels.get("max_volume", -99.0)


def syllable_count(text: str) -> int:
    return max(1, sum(1 for ch in text if is_syllable(ch)))


def check_clip(
    entry: dict, voice: str, report: Report, digests: dict[str, str], measured: dict
) -> None:
    asset = entry.get(voice)
    label = f"{entry['id']} [{voice}] {entry['text']!r}"
    if asset is None:
        report.error(f"{label}: no asset in the manifest")
        return

    path = clip_path(asset["src"])
    if not path.exists():
        report.error(f"{label}: {asset['src']} does not exist")
        return
    size = path.stat().st_size
    if size == 0:
        report.error(f"{label}: zero-byte file")
        return

    report.checked += 1
    report.total_bytes += size

    probed = measured.get(f"{entry['id']}:{voice}")
    if probed is None:
        return
    if isinstance(probed, str):
        report.error(f"{label}: does not decode ({probed})")
        return
    duration_ms, mean_db, max_db, digest = probed

    report.durations.append(int(duration_ms))

    if abs(duration_ms - asset["duration_ms"]) > 120:
        report.warn(
            f"{label}: manifest says {asset['duration_ms']} ms, file is {duration_ms:.0f} ms"
        )

    syllables = syllable_count(entry["text"])
    low = max(ABSOLUTE_MIN_MS, syllables * MS_PER_SYLLABLE_MIN)
    high = min(ABSOLUTE_MAX_MS, max(round(1200 / _TEMPO), syllables * MS_PER_SYLLABLE_MAX))
    if duration_ms < low:
        report.error(
            f"{label}: {duration_ms:.0f} ms is too short for {syllables} syllable(s) — "
            f"expected at least {low} ms"
        )
    elif duration_ms > high:
        report.warn(
            f"{label}: {duration_ms:.0f} ms is long for {syllables} syllable(s) "
            f"(over {high} ms) — check the text that was spoken"
        )

    if max_db <= SILENCE_FLOOR_DB:
        report.error(f"{label}: silent (peak {max_db:.1f} dB)")
    elif abs(mean_db - LOUDNESS_TARGET_LUFS) > LOUDNESS_TOLERANCE_DB:
        report.warn(
            f"{label}: mean {mean_db:.1f} dB is far from the {LOUDNESS_TARGET_LUFS:.0f} dB target"
        )

    digests[f"{entry['id']}:{voice}"] = digest


#: How many clips to decode at once.
#:
#: Decoding is one `ffmpeg` process per clip and the work is entirely in that
#: process, so threads here are just a way to keep several of them alive at
#: once — the GIL is held for none of it. Capped at the core count because
#: beyond that the processes queue anyway and the report's progress line starts
#: lying about how far through it is.
WORKERS = min(8, (os.cpu_count() or 2))


def probe_all(jobs: list[tuple[str, Path]]) -> dict[str, object]:
    """Decode every clip, in parallel, with a progress line.

    Split out of `check_clip` because this is the whole cost of the check —
    0.154 s of decoding each, 10,454 clips, 27 minutes in a single file-at-a-
    time loop that printed nothing until it finished. It was reported as a
    hang, and a check that looks like a hang is a check nobody runs.
    """
    results: dict[str, object] = {}
    done = 0
    with ThreadPoolExecutor(max_workers=WORKERS) as pool:
        futures = {pool.submit(_probe, path): key for key, path in jobs}
        for future in as_completed(futures):
            results[futures[future]] = future.result()
            done += 1
            if done % 250 == 0 or done == len(jobs):
                print(f"\r  decoded {done:,}/{len(jobs):,}", end="", flush=True)
    print()
    return results


def _probe(path: Path) -> object:
    try:
        duration_ms, mean_db, max_db = measure(path)
    except (RuntimeError, subprocess.CalledProcessError) as error:
        return str(error)
    return (duration_ms, mean_db, max_db, hashlib.sha256(path.read_bytes()).hexdigest())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", type=Path, default=None, help="Write the report as JSON")
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="Check a corpus outside apps/web/public/audio (for a voice change)",
    )
    parser.add_argument(
        "--sample",
        type=int,
        default=None,
        metavar="N",
        help=(
            "Decode only N clips, chosen evenly across the manifest. The "
            "manifest, plan and duplicate checks still cover everything."
        ),
    )
    args = parser.parse_args()

    global MANIFEST, AUDIO_DIR
    if args.root:
        AUDIO_DIR = args.root.resolve()
        MANIFEST = AUDIO_DIR / "manifest.json"

    if not MANIFEST.exists():
        raise SystemExit(f"{MANIFEST} is missing — run generate_audio.py first")

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))

    global _TEMPO, MS_PER_SYLLABLE_MIN, MS_PER_SYLLABLE_MAX, ABSOLUTE_MIN_MS, ABSOLUTE_MAX_MS
    _TEMPO = max(0.1, float(manifest.get("provider", {}).get("speech_rate") or SPEECH_RATE))
    MS_PER_SYLLABLE_MIN = round(90 / _TEMPO)
    MS_PER_SYLLABLE_MAX = round(900 / _TEMPO)
    ABSOLUTE_MIN_MS = round(120 / _TEMPO)
    ABSOLUTE_MAX_MS = round(12_000 / _TEMPO)
    report = Report()
    digests: dict[str, str] = {}

    jobs: list[tuple[str, Path]] = []
    for entry in manifest["entries"]:
        for voice in ("female", "male"):
            asset = entry.get(voice)
            if asset and clip_path(asset["src"]).exists():
                jobs.append((f"{entry['id']}:{voice}", clip_path(asset["src"])))

    # A sample decodes a slice and checks everything else in full.
    #
    # The distinction worth keeping: the expensive half is "does this file
    # contain the audio it claims to", and the cheap half — every id has both
    # voices, the manifest agrees with the speech plan, no two ids share a
    # recording of different text — reads no audio at all and always runs over
    # the whole set. So a sampled run is a weaker answer to one question, not a
    # partial answer to all of them.
    scanned = jobs
    if args.sample and args.sample < len(jobs):
        step = len(jobs) / args.sample
        scanned = [jobs[int(i * step)] for i in range(args.sample)]
        print(f"  sampling {len(scanned):,} of {len(jobs):,} clips for decoding")

    measured = probe_all(scanned)

    for entry in manifest["entries"]:
        for voice in ("female", "male"):
            check_clip(entry, voice, report, digests, measured)

    # The two voices must be two recordings. A retry that silently reused one
    # provider response for both would otherwise ship a "male voice" setting
    # that changes nothing, which is worse than not offering the setting.
    identical = [
        entry["id"]
        for entry in manifest["entries"]
        if digests.get(f"{entry['id']}:female")
        and digests.get(f"{entry['id']}:female") == digests.get(f"{entry['id']}:male")
    ]
    for clip_id in identical:
        report.error(f"{clip_id}: female and male clips are byte-identical")

    # Two ids with the same audio are only a bug when they say different things.
    #
    # Two reasons a shared recording is correct. Some ids are the same utterance
    # under two names: a vowel's *name* and its *sound* are both the same
    # syllable, and the block a letter lesson teaches is the same one a word
    # lesson asks for. And some different spellings are the same word out loud
    # -- 있다, 잇다 and 잊다 are all said [itda], so a speech engine given all
    # three rightly returns one recording three times.
    #
    # The comparison is therefore on the pronunciation, not the spelling. What
    # is left is the case worth catching: two genuinely different-sounding texts
    # landing on one file, which means an id collided upstream.
    text_by_id = {entry["id"]: entry["text"] for entry in manifest["entries"]}
    seen: dict[str, str] = {}
    for key, digest in digests.items():
        previous = seen.get(digest)
        if previous is not None:
            this_id, other_id = key.split(":")[0], previous.split(":")[0]
            said = romanize(text_by_id.get(this_id, ""))
            other_said = romanize(text_by_id.get(other_id, ""))
            if said != other_said:
                report.error(
                    f"{key} ({text_by_id.get(this_id)!r}) has the same audio as "
                    f"{previous} ({text_by_id.get(other_id)!r}), and they are not homophones"
                )
        seen.setdefault(digest, key)

    if PLAN.exists():
        planned = {e["id"]: e for e in json.loads(PLAN.read_text(encoding="utf-8"))["entries"]}
        manifest_ids = {e["id"] for e in manifest["entries"]}
        for clip_id, planned_entry in planned.items():
            if clip_id not in manifest_ids:
                report.error(f"{clip_id} ({planned_entry['text']!r}) was planned but never generated")
        for entry in manifest["entries"]:
            expected = planned.get(entry["id"])
            if expected and expected["text"] != entry["text"]:
                report.error(
                    f"{entry['id']}: plan says {expected['text']!r}, manifest says {entry['text']!r}"
                )
    else:
        report.warn("no speech plan cached; skipped the plan-to-manifest comparison")

    print(f"provider: {manifest['provider']['id']}")
    print(f"  female: {manifest['provider']['female_voice']}")
    print(f"  male:   {manifest['provider']['male_voice']}")

    # A manifest generated before the current rate would pass every duration
    # check here while sounding wrong in the app, because the bounds moved with
    # the constant and the audio did not.
    spoken_rate = manifest["provider"].get("speech_rate")
    provider_id = manifest["provider"].get("id", "")
    if spoken_rate is None:
        report.warn(
            "the manifest records no speech_rate — it predates the rate setting; "
            "regenerate with --force so the clips and the checks agree"
        )
    elif (declared := _declared_rate(provider_id)) is None:
        report.warn(
            f"the manifest was generated by {provider_id!r}, which is not a provider "
            "this build knows — its clips cannot be measured against a rate it declares"
        )
    elif abs(float(spoken_rate) - declared) > 1e-6:
        report.error(
            f"manifest was generated at {float(spoken_rate):g}× but {provider_id} now "
            f"declares {declared:g}× — regenerate with --force"
        )
    else:
        print(f"  rate:   {float(spoken_rate):g}×")
    print(f"checked {report.checked:,} clips, {report.total_bytes / 1_048_576:.1f} MB")
    # Said plainly, because a sampled run that reports "checked 10,550" is a
    # run that will be quoted as evidence it decoded 10,550.
    if len(measured) < report.checked:
        print(
            f"  {len(measured):,} of them decoded — the rest were checked for "
            "existence, manifest agreement and duplication only"
        )
    if report.durations:
        ordered = sorted(report.durations)
        print(
            f"  duration: min {ordered[0]} ms, median {ordered[len(ordered) // 2]} ms, "
            f"max {ordered[-1]} ms"
        )
    print(f"  {len(report.errors)} error(s), {len(report.warnings)} warning(s)")

    for message in report.warnings[:40]:
        print(f"  warn  {message}")
    if len(report.warnings) > 40:
        print(f"  … and {len(report.warnings) - 40} more warnings")
    for message in report.errors[:60]:
        print(f"  ERROR {message}")
    if len(report.errors) > 60:
        print(f"  … and {len(report.errors) - 60} more errors")

    if args.json:
        args.json.write_text(
            json.dumps(
                {
                    "checked": report.checked,
                    "decoded": len(measured),
                    "total_bytes": report.total_bytes,
                    "errors": report.errors,
                    "warnings": report.warnings,
                },
                ensure_ascii=False,
                indent=1,
            ),
            encoding="utf-8",
        )

    return 1 if report.errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
