#!/usr/bin/env node
/**
 * Inspects every page of a rendered PDF, so "the PDF was regenerated" has a
 * page-by-page record behind it rather than a page count.
 *
 *   node scripts/inspect-pdf.mjs docs/report.pdf docs/report-pdf-inspection.json
 *
 * Per page, through poppler's `pdftotext`: the character count, whether the
 * page is blank, whether any replacement character (U+FFFD — a glyph the font
 * could not draw, the tofu case) or a raw Markdown artefact (`|---`, `##`,
 * a stray backtick fence) survived into the rendered text, and whether the
 * page's Hangul rendered at all (a page whose source has Hangul but whose
 * text has none is a font failure). A summary at the top says how many pages
 * carried each finding; the report cites the summary and links this file.
 *
 * What this does not do: judge layout. `pdftoppm` renders a page to PNG on
 * request (`--png N`) so a person can look at it; the pages this pass looked at
 * are listed in the QA evidence document.
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const [pdf, out, ...rest] = process.argv.slice(2);
if (!pdf || !out) { console.error('usage: inspect-pdf.mjs <in.pdf> <out.json> [--png N,M]'); process.exit(2); }
const info = execFileSync('pdfinfo', [pdf], { encoding: 'utf8' });
const pages = Number(/Pages:\s+(\d+)/.exec(info)?.[1] ?? 0);
const results = [];
const HANGUL = /\p{Script=Hangul}/u;
for (let p = 1; p <= pages; p += 1) {
  const text = execFileSync('pdftotext', ['-f', String(p), '-l', String(p), '-layout', pdf, '-'], { encoding: 'utf8' });
  const trimmed = text.replace(/\f/g, '').trim();
  const findings = [];
  if (trimmed.length === 0) findings.push('BLANK');
  if (/�/.test(text)) findings.push('REPLACEMENT_CHARACTER');
  if (/^\s*\|\s*-{3,}/m.test(text) || /^\s*#{1,6}\s+\S/m.test(text) || /```/.test(text)) findings.push('MARKDOWN_ARTEFACT');
  results.push({ page: p, chars: trimmed.length, hangul: HANGUL.test(text), findings });
}
const summary = {
  pages,
  blank: results.filter((r) => r.findings.includes('BLANK')).length,
  replacement_character: results.filter((r) => r.findings.includes('REPLACEMENT_CHARACTER')).length,
  markdown_artefact: results.filter((r) => r.findings.includes('MARKDOWN_ARTEFACT')).length,
  pages_with_hangul: results.filter((r) => r.hangul).length,
};
writeFileSync(out, JSON.stringify({ _comment: 'GENERATED by scripts/inspect-pdf.mjs; one row per page.', pdf, inspected_at: new Date().toISOString(), summary, pages: results }, null, 1) + '\n');
const pngArg = rest.find((a) => a.startsWith('--png'));
if (pngArg) {
  const list = (rest[rest.indexOf(pngArg) + 1] ?? '').split(',').filter(Boolean);
  for (const n of list) execFileSync('pdftoppm', ['-f', n, '-l', n, '-r', '60', '-png', pdf, `${out.replace(/\.json$/, '')}-p${n}`]);
}
console.log(`${pdf}: ${pages} pages; blank ${summary.blank}, replacement characters ${summary.replacement_character}, markdown artefacts ${summary.markdown_artefact}, pages with Hangul ${summary.pages_with_hangul}`);
process.exit(summary.blank + summary.replacement_character + summary.markdown_artefact ? 1 : 0);
