/**
 * Writes the measured false-acceptance and false-rejection report.
 *
 *   npm run handwriting:robustness
 *
 * The same corpus the test gates on, printed rather than asserted, so the
 * numbers in `docs/report.md` come from a command anybody can re-run instead of
 * from a paragraph somebody wrote. Writes `docs/handwriting-robustness.json`
 * next to the prose.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { BASELINE_FONT, FIXTURE_FONTS, FIXTURE_RESOLUTION } from '../src/__tests__/fixtures.js';
import { measure } from '../src/__tests__/robustness.js';

const LETTERS = [
  'ㅏ', 'ㅓ', 'ㅗ', 'ㅜ', 'ㅡ', 'ㅣ',
  'ㄱ', 'ㄴ', 'ㄷ', 'ㄹ', 'ㅁ', 'ㅂ', 'ㅅ', 'ㅇ', 'ㅈ', 'ㅎ',
  'ㅑ', 'ㅕ', 'ㅛ', 'ㅠ',
  'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ',
  'ㅐ', 'ㅔ', 'ㅒ', 'ㅖ',
  'ㄲ', 'ㄸ', 'ㅃ', 'ㅆ', 'ㅉ',
  'ㅘ', 'ㅝ', 'ㅚ', 'ㅟ', 'ㅙ', 'ㅞ', 'ㅢ',
];

/** Mirrors `PracticeFont.evaluation` in the app. */
const FONT_GRADING: Record<string, { glyphToleranceRatio?: number }> = {
  gaegu: { glyphToleranceRatio: 0.036 },
};

const results = FIXTURE_FONTS.map((font) =>
  measure(LETTERS, font, FIXTURE_RESOLUTION, FONT_GRADING[font] ?? {}),
);

const totals = results.reduce(
  (acc, r) => ({
    genuine: acc.genuine + r.genuine,
    rejected: acc.rejected + r.genuineRejected.length,
    wrong: acc.wrong + r.impostors + r.degenerate,
    accepted: acc.accepted + r.impostorsAccepted.length + r.degenerateAccepted.length,
  }),
  { genuine: 0, rejected: 0, wrong: 0, accepted: 0 },
);

const pct = (n: number) => `${(n * 100).toFixed(2)}%`;

console.log(`Handwriting robustness — ${LETTERS.length} letters x ${FIXTURE_FONTS.length} faces`);
console.log(
  `  ${totals.genuine.toLocaleString()} genuine attempts, ${totals.wrong.toLocaleString()} wrong ones\n`,
);
console.log('  face             FRR      FAR    still confused');
for (const r of results) {
  const confusions = r.impostorsAccepted
    .map((a) => `${a.character}←${a.kind.replace('wrote ', '')}`)
    .join(' ');
  console.log(
    `  ${r.font.padEnd(15)} ${pct(r.frr).padStart(6)}  ${pct(r.far).padStart(6)}   ${confusions}`,
  );
}
console.log(
  `\n  overall          ${pct(totals.rejected / totals.genuine).padStart(6)}  ${pct(
    totals.accepted / totals.wrong,
  ).padStart(6)}`,
);

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '..', '..', '..', 'docs', 'handwriting-robustness.json');
writeFileSync(
  out,
  `${JSON.stringify(
    {
      _comment:
        'GENERATED by npm run handwriting:robustness. A synthetic adversarial corpus, not human writing samples.',
      resolution: FIXTURE_RESOLUTION,
      baseline_font: BASELINE_FONT,
      letters: LETTERS.length,
      fonts: FIXTURE_FONTS,
      genuine_attempts: totals.genuine,
      wrong_attempts: totals.wrong,
      false_rejection_rate: Number((totals.rejected / totals.genuine).toFixed(5)),
      false_acceptance_rate: Number((totals.accepted / totals.wrong).toFixed(5)),
      per_font: results.map((r) => ({
        font: r.font,
        frr: Number(r.frr.toFixed(5)),
        far: Number(r.far.toFixed(5)),
        rejected: r.genuineRejected.map((a) => `${a.character}/${a.kind}`),
        confused: r.impostorsAccepted.map((a) => `${a.character}<-${a.kind.replace('wrote ', '')}`),
      })),
    },
    null,
    1,
  )}\n`,
  'utf8',
);
console.log(`\nwrote ${out}`);
