import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link } from 'react-router-dom';
import type { VoiceGender } from '@hangyul-ganada/shared-types';

import { usePronunciation } from '../audio/PronunciationContext';
import { PRODUCT, productName } from '../config/product';
import { FONT_PREVIEW_PRIMARY, FONT_PREVIEW_SECONDARY, PRACTICE_FONTS } from '../data/fonts';
import { alphabetProgress, vocabularyProgress } from '../domain/progress';
import { invalidateGlyphCache } from '../features/writing/useEvaluator';
import { resolveContent, useFormatters, useLocale } from '../i18n';
import {
  disableReminder,
  enableReminder,
  reminderState,
  type ReminderState,
} from '../native/reminder';
import { useLearner } from '../store/LearnerContext';
import { AppHeader } from '../ui/AppHeader';
import { Button } from '../ui/Button';
import { Card } from '../ui/Card';
import { LocalizedText } from '../ui/LocalizedText';
import { Modal } from '../ui/Modal';
import { ProgressBar } from '../ui/Progress';
import { SpeakerButton } from '../ui/SpeakerButton';
import { AlertIcon, CheckIcon, ChevronRightIcon, InfoIcon, LockIcon } from '../ui/icons';
import styles from './MyPage.module.css';

/**
 * When the reminder fires, if the learner turns it on without picking a time.
 *
 * Early evening: after work or school, before the part of the night when a
 * notification is an intrusion. It is a default, not a recommendation — the
 * time picker is right there.
 */
const DEFAULT_REMINDER_TIME = '19:00';

const DAILY_TARGETS = [3, 5, 10, 15, 20];

/**
 * The clip the voice picker plays.
 *
 * One fixed greeting rather than a curriculum word, so the two voices are
 * always compared on the same sentence and the sample exists whatever the
 * vocabulary build produced. Generated by the audio pipeline like everything
 * else — see `scripts/export-speech-plan.mjs`.
 */
const VOICE_SAMPLE = { text: '안녕하세요', id: 'sample_greeting' } as const;

export function MyPage() {
  const { state, setPreferences, reset } = useLearner();
  const { provider } = usePronunciationProvider();
  const [confirmReset, setConfirmReset] = useState(false);
  const { t } = useTranslation(['settings', 'common']);
  const { locale, descriptor } = useLocale();
  const format = useFormatters();

  const alphabet = alphabetProgress(state.progress);
  const vocabulary = vocabularyProgress(state.progress);
  /**
   * Days the learner has studied.
   *
   * A row in the activity map is written the first time something happens on a
   * given day and never otherwise — see `domain/activity.ts` — so counting the
   * rows counts the days, without a second record to keep in step.
   */
  const studyDays = Object.keys(state.activity).length;

  const selectFont = (id: string) => {
    setPreferences({ selected_font_id: id });
    // The reference mask is rendered from the selected face, so cached masks
    // from the previous one would grade against the wrong shape.
    invalidateGlyphCache();
  };

  const selectVoice = (voice: VoiceGender) => {
    setPreferences({ voice });
  };

  return (
    <div className={styles.page}>
      <AppHeader title={t('settings:title')} />

      <div className={styles.body}>
        {/*
          Three numbers, all of them things the learner did.

          This card used to read `Letters 8/40`, `Words 0/2,581`, `Sessions 0`.
          Two of those were wrong in different ways. The vocabulary denominator
          is a fact about the catalogue rather than about the learner, and
          putting `0 / 2,581` in the largest type on the screen tells someone on
          their third day that they have 2,581 words *left* — which is true,
          discouraging, and not what they opened this screen to find out. And
          "Sessions" counted rows in a table: nobody has ever wanted to know
          they completed seven sessions, and it cannot be acted on.

          What is left is three counts that only go up and that a learner
          recognises as their own work. The alphabet bar underneath still shows
          the 40 letters as a proportion, because 40 is a number a beginner can
          hold in their head and finishing it is a real milestone.
        */}
        <Card tone="warm" padding="lg" className={styles.stats}>
          <div className={styles.statRow}>
            <Stat
              label={t('settings:stats.lettersLearned')}
              value={format.number(alphabet.done)}
            />
            <Stat
              label={t('settings:stats.wordsLearned')}
              value={format.number(vocabulary.done)}
            />
            <Stat label={t('settings:stats.studyDays')} value={format.number(studyDays)} />
          </div>
          <div className={styles.statProgress}>
            <ProgressBar
              value={alphabet.ratio}
              label={t('settings:stats.alphabetProgress')}
              hideLabel={false}
            />
          </div>
        </Card>

        {/*
          The two things that can go wrong with a learner's record, and nothing
          else about where it is kept.

          Both are silent failures otherwise: a browser in private mode throws
          away everything on close, and a damaged row is skipped so the rest can
          load. Neither happens on a healthy install, so neither is shown then —
          this is a warning, not a status readout.
        */}
        {!state.storage.durable && (
          <p className={styles.storageWarning} role="status">
            <AlertIcon size={16} />
            {t('settings:storage.notSaving')}
          </p>
        )}
        {state.recovered > 0 && (
          <p className={styles.storageWarning} role="status">
            <AlertIcon size={16} />
            {t('settings:storage.recovered', { count: state.recovered })}
          </p>
        )}

        {/*
          Five groups, ordered by why someone opens this screen.

          The old screen was seven numbered sections in a flat list, which made
          it a scroll rather than a place — a learner looking for the guide-line
          toggle read four headings about voices and daily targets to get to it,
          and the numbering implied a sequence that does not exist. Grouping
          means the three quarters of the screen that are not what they came for
          can be skipped in one glance.

          What a learner is doing comes first, then how practice feels, then how
          it looks, then the app's own settings, and the one irreversible action
          is on its own at the bottom where nothing is next to it to mis-tap.
        */}
        <Group id="settings-learning" title={t('settings:groups.learning')}>
          <Link to="/me/activity" className={styles.linkRow}>
            <span className={styles.linkText}>
              <span className={styles.linkTitle}>{t('settings:activity.title')}</span>
              <span className={styles.linkBody}>{t('settings:activity.body')}</span>
            </span>
            <ChevronRightIcon size={18} />
          </Link>
          <Section
            title={t('settings:dailyTarget.title')}
            description={t('settings:dailyTarget.description')}
          >
            <div className={styles.targetRow}>
              {DAILY_TARGETS.map((n) => (
                <button
                  key={n}
                  type="button"
                  className={`${styles.targetOption} ${
                    state.settings.daily_target === n ? styles.targetSelected : ''
                  }`}
                  onClick={() => setPreferences({ daily_target: n })}
                  aria-pressed={state.settings.daily_target === n}
                  aria-label={t('settings:dailyTarget.optionAria', { count: n })}
                >
                  {t('settings:dailyTarget.option', { count: n })}
                </button>
              ))}
            </div>
          </Section>

        </Group>

        <Group id="settings-practice" title={t('settings:groups.practice')}>
          {/*
            How much of the model to keep on the paper. Both options show the
            character — see `domain/mastery.ts` — so this changes the pace of a
            lesson rather than whether it can be finished.
          */}
          <Section
            title={t('settings:style.title')}
            description={t('settings:style.description')}
          >
            <div className={styles.modeRow}>
              <ModeOption
                selected={state.settings.practice_style === 'guided'}
                onClick={() => setPreferences({ practice_style: 'guided' })}
                title={t('settings:style.guided.title')}
                detail={t('settings:style.guided.detail')}
              />
              <ModeOption
                selected={state.settings.practice_style === 'focused'}
                onClick={() => setPreferences({ practice_style: 'focused' })}
                title={t('settings:style.focused.title')}
                detail={t('settings:style.focused.detail')}
              />
            </div>
          </Section>
          {/*
            The pronunciation voice. Second, because it is the setting a learner
            most often wants to change and the one they will look for: hearing a
            voice you find hard to follow, in an app whose whole subject is
            sound, is a reason to stop using it.
          */}
          <Section
            title={t('settings:voice.title')}
            description={t('settings:voice.description')}
          >
            <div className={styles.voiceRow}>
              {(['female', 'male'] as const).map((voice) => (
                <button
                  key={voice}
                  type="button"
                  className={`${styles.voiceOption} ${
                    state.settings.voice === voice ? styles.voiceSelected : ''
                  }`}
                  onClick={() => selectVoice(voice)}
                  aria-pressed={state.settings.voice === voice}
                >
                  <span className={styles.voiceName}>{t(`settings:voice.${voice}`)}</span>
                  <span className={styles.voiceSample} lang="ko" dir="ltr">
                    {VOICE_SAMPLE.text}
                  </span>
                  {state.settings.voice === voice && (
                    <span className={styles.voiceCheck} aria-hidden="true">
                      <CheckIcon size={16} />
                    </span>
                  )}
                </button>
              ))}
            </div>
            <div className={styles.voicePreview}>
              <span>{t('settings:voice.preview')}</span>
              <SpeakerButton
                audioId={VOICE_SAMPLE.id}
                label={VOICE_SAMPLE.text}
                size="md"
              />
            </div>
            {/*
              There was a "play automatically" switch here. It is gone, and not
              because it was unpopular: a listening question is a clip and three
              letters, and a learner who had once turned this off arrived at one
              in silence with no way of knowing what the question was. A setting
              that can break a screen is not a setting. The stored field stays
              where it is, unread, so that no profile has to be migrated for a
              switch that no longer exists — see `audio/useEntryAudio.ts`.
            */}
            {provider && (
              <p className={styles.sourceNote}>
                {t('settings:voice.provider', {
                  female: provider.female_voice,
                  male: provider.male_voice,
                })}
              </p>
            )}
          </Section>
          <Section
            title={t('settings:font.title')}
            description={t('settings:font.description')}
          >
            <ul className={styles.fontList}>
              {PRACTICE_FONTS.map((font) => {
                const selected = font.id === state.settings.selected_font_id;
                const description = resolveContent(font.translations, locale);
                return (
                  <li key={font.id}>
                    <button
                      type="button"
                      className={`${styles.fontOption} ${selected ? styles.fontSelected : ''}`}
                      onClick={() => selectFont(font.id)}
                      aria-pressed={selected}
                    >
                      {/*
                        The preview is the control, not decoration beside it. A
                        learner cannot choose between 명조체 and 바탕체 from the
                        words "Myeongjo" and "Traditional" — they choose by
                        looking at 가나다 in each, so it is set large enough to
                        show what actually differs between the faces.

                        Rendered with the real family, which is loaded eagerly in
                        `styles/fonts.ts`; a preview drawn in a fallback face
                        would be an outright lie about the choice being made.
                      */}
                      <span
                        className={styles.fontPreview}
                        style={{ fontFamily: font.font_family, fontWeight: font.weight }}
                        aria-hidden="true"
                      >
                        <span className={styles.fontPreviewLg} lang="ko">
                          {FONT_PREVIEW_PRIMARY}
                        </span>
                        <span className={styles.fontPreviewSm} lang="ko">
                          {FONT_PREVIEW_SECONDARY}
                        </span>
                      </span>
                      <span className={styles.fontMeta}>
                        {/*
                          Name and Korean name, and no category badge beside
                          them: the options are *named* after their styles, so a
                          "Rounded" row tagged "Rounded" was the same word twice.
                        */}
                        <span className={styles.fontNameRow}>
                          <span className={styles.fontName}>{font.name_en}</span>
                          {/* The Korean name of the style, for a learner who will
                              meet it named that way everywhere else. */}
                          <span className={styles.fontNameKo} lang="ko" dir="ltr">
                            {font.name}
                          </span>
                        </span>
                        <LocalizedText as="span" locale={description.locale} className={styles.fontDesc}>
                          {description.value.description}
                        </LocalizedText>
                        <span className={styles.fontLicense}>
                          {font.family_name} · {font.license_short}
                        </span>
                      </span>
                      {selected && (
                        <span className={styles.fontCheck} aria-hidden="true">
                          <CheckIcon size={16} />
                        </span>
                      )}
                    </button>
                  </li>
                );
              })}
            </ul>
          </Section>
          <Section
            title={t('settings:guides.title')}
            description={t('settings:guides.description')}
          >
            <ul className={styles.toggleList}>
              <Toggle
                label={t('settings:guides.grid')}
                checked={state.settings.show_grid}
                onChange={(v) => setPreferences({ show_grid: v })}
              />
              <Toggle
                label={t('settings:guides.crosshair')}
                checked={state.settings.show_center_crosshair}
                onChange={(v) => setPreferences({ show_center_crosshair: v })}
              />
            </ul>
          </Section>

        </Group>

        <Group id="settings-appearance" title={t('settings:groups.appearance')}>
          <Section
            title={t('settings:appearance.title')}
            description={t('settings:appearance.description')}
          >
            <div
              className={styles.appearanceRow}
              role="radiogroup"
              aria-label={t('settings:appearance.title')}
            >
              {(['system', 'light', 'dark'] as const).map((choice) => (
                <button
                  key={choice}
                  type="button"
                  role="radio"
                  aria-checked={state.settings.appearance === choice}
                  className={`${styles.appearanceOption} ${
                    state.settings.appearance === choice ? styles.appearanceSelected : ''
                  }`}
                  onClick={() => setPreferences({ appearance: choice })}
                >
                  <span className={styles.appearanceSwatch} data-appearance={choice} aria-hidden="true" />
                  <span className={styles.appearanceName}>
                    {t(`settings:appearance.${choice}`)}
                  </span>
                </button>
              ))}
            </div>
          </Section>
        </Group>

        <Group id="settings-app" title={t('settings:groups.app')}>
          {/* Language comes first: it is the setting that changes every other
              word on the screen, so burying it under the font picker would be
              perverse for someone who cannot read the current language. */}
          <Section
            title={t('settings:language.title')}
            description={t('settings:language.description')}
          >
            <Link to="/me/language" className={styles.languageRow}>
              <span className={styles.languageNames}>
                <span className={styles.languageNative} lang={descriptor.code}>
                  <bdi>{descriptor.nativeName}</bdi>
                </span>
                {descriptor.englishName !== descriptor.nativeName && (
                  <span className={styles.languageEnglish}>
                    <bdi>{descriptor.englishName}</bdi>
                  </span>
                )}
              </span>
              <span className={styles.languageAction}>
                {t('settings:language.openPicker')}
                <ChevronRightIcon size={18} />
              </span>
            </Link>
          </Section>

          {/*
            The daily reminder.

            Native only — a browser tab cannot set an alarm on a phone, and
            offering a switch that silently does nothing would be worse than not
            offering one. Off until the learner turns it on, and the system
            permission prompt appears at that moment and no earlier: see
            `native/reminder.ts`.
          */}
          <DailyReminder />

          {/*
            Privacy and licences, as two rows near the bottom.

            This screen used to carry a group headed "Your progress stays with
            you on this device" with three bullet points under it explaining
            that there is no account, that nothing is uploaded, and that the
            learner's copy is theirs. All of it was true and none of it is what
            a settings screen is for: it is the product explaining its own
            architecture to someone who bought a Korean course. The policy it
            was paraphrasing still exists, in full, one tap away — which is
            where a privacy policy belongs.
          */}
          <Link to="/me/privacy" className={styles.linkRow}>
            <span className={styles.linkIcon}>
              <LockIcon size={18} />
            </span>
            <span className={styles.linkText}>
              <span className={styles.linkTitle}>{t('settings:privacy.title')}</span>
              <span className={styles.linkBody}>{t('settings:privacy.body')}</span>
            </span>
            <ChevronRightIcon size={18} />
          </Link>

          <Link to="/me/legal" className={styles.linkRow}>
            <span className={styles.linkIcon}>
              <InfoIcon size={18} />
            </span>
            <span className={styles.linkText}>
              <span className={styles.linkTitle}>{t('settings:legal.title')}</span>
              <span className={styles.linkBody}>{t('settings:legal.body')}</span>
            </span>
            <ChevronRightIcon size={18} />
          </Link>

          <Card padding="md" className={styles.about}>
            <p className={styles.aboutTitle}>{productName(locale)}</p>
            <p className={styles.aboutBody}>{t('settings:about.body')}</p>
            {/*
              The line that explained the grading threshold — "more than 55%
              different and it asks for another go" — is gone. It answered a
              question nobody asks about a product they are using, and the
              number is meaningless without the rest of the evaluator. What a
              learner wants from About is what this is, whether it works on a
              plane, and which version they are on.
            */}
            <p className={styles.aboutNote}>{t('settings:about.offline')}</p>
            <p className={styles.aboutVersion}>
              {t('settings:about.version', { version: PRODUCT.version })}
            </p>
          </Card>
        </Group>

        {/*
          The one action on this screen that cannot be taken back, on its own at
          the end of it.

          It used to sit inside the data section between "Save a copy" and
          "Restore a copy", which put a destructive button a thumb's width from
          two harmless ones. Now there is nothing next to it to mis-tap, and the
          confirmation in front of it says what will be lost rather than asking
          whether the learner is sure.
        */}
        <Group id="settings-reset" title={t('settings:groups.reset')}>
          <Section description={t('settings:reset.body')}>
            <Button
              variant="ghost"
              size="md"
              pill
              className={styles.dataReset}
              onClick={() => setConfirmReset(true)}
            >
              {t('settings:about.reset')}
            </Button>
          </Section>
        </Group>
      </div>

      <Modal
        open={confirmReset}
        onClose={() => setConfirmReset(false)}
        title={t('settings:reset.title')}
        description={t('settings:reset.description')}
        footer={
          <>
            <Button
              size="lg"
              fullWidth
              onClick={() => {
                void reset();
                setConfirmReset(false);
              }}
            >
              {t('settings:reset.confirm')}
            </Button>
            <Button size="lg" variant="ghost" fullWidth onClick={() => setConfirmReset(false)}>
              {t('settings:reset.cancel')}
            </Button>
          </>
        }
      >
        <span className="hg-sr-only">{t('common:a11y.confirmationRequired')}</span>
      </Modal>
    </div>
  );
}

/** Narrow wrapper, so this file reaches for one thing rather than the player. */
function usePronunciationProvider() {
  const { player } = usePronunciation();
  return { provider: player.provider };
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className={styles.stat}>
      <span className={styles.statLabel}>{label}</span>
      <span className={styles.statValue}>{value}</span>
    </div>
  );
}

/**
 * The optional daily reminder.
 *
 * Renders nothing at all off-device, and nothing until it has asked the
 * platform whether it can. A row that appears and then disappears is worse than
 * one that never appeared, so the state is resolved before the first paint of
 * the row rather than after it.
 */
function DailyReminder() {
  const { t } = useTranslation(['settings']);
  const [state, setState] = useState<ReminderState | null>(null);
  const [refused, setRefused] = useState(false);

  useEffect(() => {
    void reminderState().then(setState);
  }, []);

  if (!state?.available) return null;

  const on = state.at !== null;
  const time = state.at ?? DEFAULT_REMINDER_TIME;

  const apply = async (next: { on: boolean; at: string }) => {
    if (!next.on) {
      await disableReminder();
      setRefused(false);
      setState({ ...state, at: null });
      return;
    }
    const granted = await enableReminder(next.at, {
      title: t('settings:reminder.notificationTitle'),
      body: t('settings:reminder.notificationBody'),
    });
    setRefused(!granted);
    setState({ ...state, at: granted ? next.at : null });
  };

  return (
    <Section
      title={t('settings:reminder.title')}
      description={t('settings:reminder.description')}
    >
      <ul className={styles.toggleList}>
        <Toggle
          label={t('settings:reminder.toggle')}
          checked={on}
          onChange={(value) => void apply({ on: value, at: time })}
        />
        {on && (
          <li className={styles.toggleRow}>
            <label className={styles.toggleLabel}>
              <span className={styles.toggleText}>{t('settings:reminder.at')}</span>
              <input
                type="time"
                className={styles.timeInput}
                value={time}
                onChange={(event) => void apply({ on: true, at: event.target.value })}
              />
            </label>
          </li>
        )}
      </ul>
      {refused && (
        <p className={styles.sectionDesc} role="status">
          {t('settings:reminder.refused')}
        </p>
      )}
    </Section>
  );
}

/** Numbered section header, matching the level-select screen in the design. */
/**
 * One setting, inside a group.
 *
 * ## Why the numbers went
 *
 * Every section used to carry a number, one to seven. Numbering a list tells a
 * reader it is a sequence — step 1, then step 2 — and settings are not a
 * sequence: nobody sets their daily target *after* choosing a voice and
 * *before* exporting their data. The numbering also made the order load-bearing
 * in a way it was not, so adding a setting meant renumbering three others.
 *
 * What a settings screen actually needs is grouping, so a learner looking for
 * the guide-lines toggle can skip four groups without reading them. See
 * `Group` below.
 */
function Section({
  title,
  description,
  children,
}: {
  /** Omitted where the group heading is already the only heading needed. */
  title?: string;
  description?: string;
  children: React.ReactNode;
}) {
  return (
    <section className={styles.section}>
      {title && <h3 className={styles.sectionTitle}>{title}</h3>}
      {description && <p className={styles.sectionDesc}>{description}</p>}
      {children}
    </section>
  );
}

/**
 * A band of related settings, with a heading a learner can scan past.
 *
 * The groups are ordered by how often someone opens this screen for them: what
 * they are learning, then what practice feels like, then how it looks, then the
 * app's own settings, and last the one thing that undoes all of it.
 */
function Group({
  id,
  title,
  children,
}: {
  id: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className={styles.group} role="group" aria-labelledby={id}>
      <h2 id={id} className={styles.groupTitle}>
        {title}
      </h2>
      {children}
    </div>
  );
}

function ModeOption({
  selected,
  onClick,
  title,
  detail,
}: {
  selected: boolean;
  onClick: () => void;
  title: string;
  detail: string;
}) {
  return (
    <button
      type="button"
      className={`${styles.modeOption} ${selected ? styles.modeSelected : ''}`}
      onClick={onClick}
      aria-pressed={selected}
    >
      <span className={styles.modeTitle}>{title}</span>
      <span className={styles.modeDetail}>{detail}</span>
    </button>
  );
}

function Toggle({
  label,
  hint,
  checked,
  onChange,
}: {
  label: string;
  hint?: string;
  checked: boolean;
  onChange: (value: boolean) => void;
}) {
  return (
    <li className={styles.toggleRow}>
      <label className={styles.toggleLabel}>
        <span className={styles.toggleText}>
          <span>{label}</span>
          {hint && <span className={styles.toggleHint}>{hint}</span>}
        </span>
        <input
          type="checkbox"
          className={styles.toggleInput}
          checked={checked}
          onChange={(e) => onChange(e.target.checked)}
        />
        <span className={styles.toggleTrack} aria-hidden="true">
          <span className={styles.toggleThumb} />
        </span>
      </label>
    </li>
  );
}
